sudo: false
language: php
matrix:
  fast_finish: true
  include:
  # - php: '5.2'
  # - php: '5.6'
  #   env: SNIFF=1
  # - php: '7.0'
  # - php: '7.1'
  - php: nightly
  - php: hhvm
  allow_failures:
  - php: hhvm
before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git
  $PHPCS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git
  $SNIFFS_DIR/PHPCompatibility; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs --config-set installed_paths
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g jscs; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g jshint; fi
- if [[ "$SNIFF" == "1" ]]; then wget https://develop.svn.wordpress.org/trunk/.jshintrc;
  fi
script:
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- if [[ "$SNIFF" == "1" ]]; then jshint .; fi
- if [[ "$SNIFF" == "1" ]]; then jscs .; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml
  --extensions=php; fi
deploy:
  provider: heroku
  api_key:
    secure: xe7CfU3EzGNvA1zggA8GmGUSFBns+80u42l/6wNrsPAB6W7ELzK47zl1PqEs2y+t/n1s8l7+wQX/xCdzv9cmFto0Ml00jS21rDw9Ja68bRITH5j6a2elPb4oj3Nsd4wAWgC9t0QGZv5nP5hHJi2XQSsp325x55lbgUEYGpQMjoozF9dXlOa8zb7wp6qyitNxQfy0faeyfkgNmvLBWlrTdhDkpT4KuhJPii/Dn/GTfwrOS4nh8jD7mzJMxxpXhWnIFnpVhPJcni0oi6obno+1O7uAx0e41XQyiwqcG7IObFwd7BSPPGA63qA5UZ6Q6OKj4JS4t2NFvcVQAsIwwJ2coltgcm89U/XAzuieGo9q7TaDBSduZtTJWSAbbfNDiRIT3KEdrvzYPitV1Tb+jGDQ94imFjO+4SuV2JEG8j2ABexL30yS342fMhjsZCyOt3clG2gnTEK2QDroJvNtgJoTLjd8MxWaqjPM+7Chfv6hBszBbvqY/yi/xdggAzkVTrgtvoXq7lNOEBOcJF39gbq5l/A5xTmOoWYnrBIM2ZCcbQz9//dL9OQye+YLAH3yc0EzC11iVm5d5XeunsifDque51I/H+I150SXV4rFwU3HYCBmn6af6yXkcWye1/imj2yLmSHg+rT2hjgAsSuP0kxwTufeDq9zBg2kpkTNgoQogbI=
  app: codespa
  on:
    all_branches: true    