version: '2'
services:
  nginx:
    image: nginx:1.11
    ports:
      - "80:80"
    links:
      - mysql
      - fpm
    volumes:
      - ./www/wordpress:/var/www/wordpress
      - ./configures/conf.d:/etc/nginx/conf.d:ro

  mysql:
    image: mysql:5.7
    volumes:
       - ./data/mysql:/var/lib/mysql
       - ./data-dump/wordpress.sql:/docker-entrypoint-initdb.d/wordpress.sql  # Trying to import data
      #  - mysql_conf:/etc/mysql  # Making MYSQL configuratons persistent
    # command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      # - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=codespa
      - MYSQL_USER=root
      # - MYSQL_PASSWORD=testerpw
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  fpm:
    build: images/nginxphp
    volumes:
      - ./www/wordpress:/var/www/wordpress
    links:
      - mysql

# volumes:
#     mysql_conf: